packages:
  - "apps/*"
allowBuilds:
  "@scarf/scarf": false
  better-sqlite3: true
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - "@copilotkit/a2ui-renderer@1.61.1"
  - "@copilotkit/core@1.61.1"
  - "@copilotkit/react-core@1.61.1"
  - "@copilotkit/react-textarea@1.61.1"
  - "@copilotkit/react-ui@1.61.1"
  - "@copilotkit/runtime-client-gql@1.61.1"
  - "@copilotkit/runtime@1.61.1"
  - "@copilotkit/shared@1.61.1"
  - "@copilotkit/web-inspector@1.61.1"
  - "@copilotkit/sdk-js@1.61.1"
